# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ytdlp.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 700))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.downloadTab = QtWidgets.QWidget()
        self.downloadTab.setObjectName("downloadTab")
        self.downloadTabLayout = QtWidgets.QVBoxLayout(self.downloadTab)
        self.downloadTabLayout.setObjectName("downloadTabLayout")
        self.urlGroup = QtWidgets.QGroupBox(self.downloadTab)
        self.urlGroup.setObjectName("urlGroup")
        self.urlLayout = QtWidgets.QVBoxLayout(self.urlGroup)
        self.urlLayout.setObjectName("urlLayout")
        self.urlInputLayout = QtWidgets.QHBoxLayout()
        self.urlInputLayout.setObjectName("urlInputLayout")
        self.label = QtWidgets.QLabel(self.urlGroup)
        self.label.setMinimumSize(QtCore.QSize(80, 0))
        self.label.setObjectName("label")
        self.urlInputLayout.addWidget(self.label)
        self.videoUrl = QtWidgets.QLineEdit(self.urlGroup)
        self.videoUrl.setObjectName("videoUrl")
        self.urlInputLayout.addWidget(self.videoUrl)
        self.clearUrlBtn = QtWidgets.QPushButton(self.urlGroup)
        self.clearUrlBtn.setMaximumSize(QtCore.QSize(80, 16777215))
        self.clearUrlBtn.setObjectName("clearUrlBtn")
        self.urlInputLayout.addWidget(self.clearUrlBtn)
        self.urlLayout.addLayout(self.urlInputLayout)
        self.downloadButtonLayout = QtWidgets.QHBoxLayout()
        self.downloadButtonLayout.setObjectName("downloadButtonLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.downloadButtonLayout.addItem(spacerItem)
        self.downloadBtn = QtWidgets.QPushButton(self.urlGroup)
        self.downloadBtn.setMinimumSize(QtCore.QSize(150, 45))
        self.downloadBtn.setMaximumSize(QtCore.QSize(200, 45))
        self.downloadBtn.setObjectName("downloadBtn")
        self.downloadButtonLayout.addWidget(self.downloadBtn)
        self.cancelBtn = QtWidgets.QPushButton(self.urlGroup)
        self.cancelBtn.setEnabled(False)
        self.cancelBtn.setMinimumSize(QtCore.QSize(150, 45))
        self.cancelBtn.setMaximumSize(QtCore.QSize(200, 45))
        self.cancelBtn.setObjectName("cancelBtn")
        self.downloadButtonLayout.addWidget(self.cancelBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.downloadButtonLayout.addItem(spacerItem1)
        self.urlLayout.addLayout(self.downloadButtonLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.urlLayout.addItem(spacerItem2)
        self.downloadTabLayout.addWidget(self.urlGroup)
        self.progressGroup = QtWidgets.QGroupBox(self.downloadTab)
        self.progressGroup.setVisible(False)
        self.progressGroup.setObjectName("progressGroup")
        self.progressLayout = QtWidgets.QVBoxLayout(self.progressGroup)
        self.progressLayout.setObjectName("progressLayout")
        self.progressBarLayout = QtWidgets.QHBoxLayout()
        self.progressBarLayout.setObjectName("progressBarLayout")
        self.downloadStatus = QtWidgets.QProgressBar(self.progressGroup)
        self.downloadStatus.setProperty("value", 0)
        self.downloadStatus.setObjectName("downloadStatus")
        self.progressBarLayout.addWidget(self.downloadStatus)
        self.progressLabel = QtWidgets.QLabel(self.progressGroup)
        self.progressLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.progressLabel.setObjectName("progressLabel")
        self.progressBarLayout.addWidget(self.progressLabel)
        self.progressLayout.addLayout(self.progressBarLayout)
        self.logText = QtWidgets.QTextEdit(self.progressGroup)
        self.logText.setReadOnly(True)
        self.logText.setObjectName("logText")
        self.progressLayout.addWidget(self.logText)
        self.downloadTabLayout.addWidget(self.progressGroup)
        self.contactGroup = QtWidgets.QGroupBox(self.downloadTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contactGroup.sizePolicy().hasHeightForWidth())
        self.contactGroup.setSizePolicy(sizePolicy)
        self.contactGroup.setObjectName("contactGroup")
        self.contactLayout = QtWidgets.QVBoxLayout(self.contactGroup)
        self.contactLayout.setObjectName("contactLayout")
        self.adLayout = QtWidgets.QHBoxLayout()
        self.adLayout.setObjectName("adLayout")
        self.adLeftLayout = QtWidgets.QVBoxLayout()
        self.adLeftLayout.setObjectName("adLeftLayout")
        self.adLabel = QtWidgets.QLabel(self.contactGroup)
        self.adLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.adLabel.setObjectName("adLabel")
        self.adLeftLayout.addWidget(self.adLabel)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.websiteBtn = QtWidgets.QPushButton(self.contactGroup)
        self.websiteBtn.setMinimumSize(QtCore.QSize(90, 28))
        self.websiteBtn.setMaximumSize(QtCore.QSize(110, 28))
        self.websiteBtn.setObjectName("websiteBtn")
        self.buttonLayout.addWidget(self.websiteBtn)
        self.contactPageBtn = QtWidgets.QPushButton(self.contactGroup)
        self.contactPageBtn.setMinimumSize(QtCore.QSize(90, 28))
        self.contactPageBtn.setMaximumSize(QtCore.QSize(110, 28))
        self.contactPageBtn.setObjectName("contactPageBtn")
        self.buttonLayout.addWidget(self.contactPageBtn)
        self.adLeftLayout.addLayout(self.buttonLayout)
        self.adLayout.addLayout(self.adLeftLayout)
        spacerItem3 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.adLayout.addItem(spacerItem3)
        self.qrLayout = QtWidgets.QHBoxLayout()
        self.qrLayout.setObjectName("qrLayout")
        self.qqGroup = QtWidgets.QGroupBox(self.contactGroup)
        self.qqGroup.setMaximumSize(QtCore.QSize(180, 220))
        self.qqGroup.setObjectName("qqGroup")
        self.qqGroupLayout = QtWidgets.QVBoxLayout(self.qqGroup)
        self.qqGroupLayout.setContentsMargins(6, 10, 6, 6)
        self.qqGroupLayout.setSpacing(4)
        self.qqGroupLayout.setObjectName("qqGroupLayout")
        self.qqQrLabel = QtWidgets.QLabel(self.qqGroup)
        self.qqQrLabel.setMinimumSize(QtCore.QSize(150, 150))
        self.qqQrLabel.setMaximumSize(QtCore.QSize(150, 150))
        self.qqQrLabel.setScaledContents(True)
        self.qqQrLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.qqQrLabel.setObjectName("qqQrLabel")
        self.qqGroupLayout.addWidget(self.qqQrLabel)
        self.qqInfoLabel = QtWidgets.QLabel(self.qqGroup)
        self.qqInfoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.qqInfoLabel.setObjectName("qqInfoLabel")
        self.qqGroupLayout.addWidget(self.qqInfoLabel)
        self.qrLayout.addWidget(self.qqGroup)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.qrLayout.addItem(spacerItem4)
        self.wechatGroup = QtWidgets.QGroupBox(self.contactGroup)
        self.wechatGroup.setMaximumSize(QtCore.QSize(180, 220))
        self.wechatGroup.setObjectName("wechatGroup")
        self.wechatGroupLayout = QtWidgets.QVBoxLayout(self.wechatGroup)
        self.wechatGroupLayout.setContentsMargins(6, 10, 6, 6)
        self.wechatGroupLayout.setSpacing(4)
        self.wechatGroupLayout.setObjectName("wechatGroupLayout")
        self.wechatQrLabel = QtWidgets.QLabel(self.wechatGroup)
        self.wechatQrLabel.setMinimumSize(QtCore.QSize(150, 150))
        self.wechatQrLabel.setMaximumSize(QtCore.QSize(150, 150))
        self.wechatQrLabel.setScaledContents(True)
        self.wechatQrLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.wechatQrLabel.setObjectName("wechatQrLabel")
        self.wechatGroupLayout.addWidget(self.wechatQrLabel)
        self.wechatInfoLabel = QtWidgets.QLabel(self.wechatGroup)
        self.wechatInfoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.wechatInfoLabel.setObjectName("wechatInfoLabel")
        self.wechatGroupLayout.addWidget(self.wechatInfoLabel)
        self.qrLayout.addWidget(self.wechatGroup)
        self.adLayout.addLayout(self.qrLayout)
        self.contactLayout.addLayout(self.adLayout)
        self.downloadTabLayout.addWidget(self.contactGroup)
        self.tabWidget.addTab(self.downloadTab, "")
        self.settingsTab = QtWidgets.QWidget()
        self.settingsTab.setObjectName("settingsTab")
        self.settingsTabLayout = QtWidgets.QVBoxLayout(self.settingsTab)
        self.settingsTabLayout.setObjectName("settingsTabLayout")
        self.pathGroup = QtWidgets.QGroupBox(self.settingsTab)
        self.pathGroup.setObjectName("pathGroup")
        self.pathGroupLayout = QtWidgets.QVBoxLayout(self.pathGroup)
        self.pathGroupLayout.setObjectName("pathGroupLayout")
        self.pathLayout = QtWidgets.QHBoxLayout()
        self.pathLayout.setObjectName("pathLayout")
        self.pathLabel = QtWidgets.QLabel(self.pathGroup)
        self.pathLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.pathLabel.setObjectName("pathLabel")
        self.pathLayout.addWidget(self.pathLabel)
        self.pathEdit = QtWidgets.QLineEdit(self.pathGroup)
        self.pathEdit.setReadOnly(True)
        self.pathEdit.setObjectName("pathEdit")
        self.pathLayout.addWidget(self.pathEdit)
        self.browsePathBtn = QtWidgets.QPushButton(self.pathGroup)
        self.browsePathBtn.setMaximumSize(QtCore.QSize(120, 16777215))
        self.browsePathBtn.setObjectName("browsePathBtn")
        self.pathLayout.addWidget(self.browsePathBtn)
        self.pathGroupLayout.addLayout(self.pathLayout)
        self.pathHintLabel = QtWidgets.QLabel(self.pathGroup)
        self.pathHintLabel.setObjectName("pathHintLabel")
        self.pathGroupLayout.addWidget(self.pathHintLabel)
        self.settingsTabLayout.addWidget(self.pathGroup)
        self.formatGroup = QtWidgets.QGroupBox(self.settingsTab)
        self.formatGroup.setObjectName("formatGroup")
        self.formatGroupLayout = QtWidgets.QVBoxLayout(self.formatGroup)
        self.formatGroupLayout.setObjectName("formatGroupLayout")
        self.formatLayout = QtWidgets.QHBoxLayout()
        self.formatLayout.setObjectName("formatLayout")
        self.formatLabel = QtWidgets.QLabel(self.formatGroup)
        self.formatLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.formatLabel.setObjectName("formatLabel")
        self.formatLayout.addWidget(self.formatLabel)
        self.formatCombo = QtWidgets.QComboBox(self.formatGroup)
        self.formatCombo.setObjectName("formatCombo")
        self.formatCombo.addItem("")
        self.formatCombo.addItem("")
        self.formatCombo.addItem("")
        self.formatCombo.addItem("")
        self.formatCombo.addItem("")
        self.formatCombo.addItem("")
        self.formatCombo.addItem("")
        self.formatCombo.addItem("")
        self.formatLayout.addWidget(self.formatCombo)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formatLayout.addItem(spacerItem5)
        self.formatGroupLayout.addLayout(self.formatLayout)
        self.formatHintLabel = QtWidgets.QLabel(self.formatGroup)
        self.formatHintLabel.setObjectName("formatHintLabel")
        self.formatGroupLayout.addWidget(self.formatHintLabel)
        self.settingsTabLayout.addWidget(self.formatGroup)
        self.optionsGroup = QtWidgets.QGroupBox(self.settingsTab)
        self.optionsGroup.setObjectName("optionsGroup")
        self.optionsGroupLayout = QtWidgets.QVBoxLayout(self.optionsGroup)
        self.optionsGroupLayout.setObjectName("optionsGroupLayout")
        self.optionsLayout1 = QtWidgets.QHBoxLayout()
        self.optionsLayout1.setObjectName("optionsLayout1")
        self.subtitleCheck = QtWidgets.QCheckBox(self.optionsGroup)
        self.subtitleCheck.setObjectName("subtitleCheck")
        self.optionsLayout1.addWidget(self.subtitleCheck)
        self.subtitleHintLabel = QtWidgets.QLabel(self.optionsGroup)
        self.subtitleHintLabel.setObjectName("subtitleHintLabel")
        self.optionsLayout1.addWidget(self.subtitleHintLabel)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.optionsLayout1.addItem(spacerItem6)
        self.optionsGroupLayout.addLayout(self.optionsLayout1)
        self.optionsLayout2 = QtWidgets.QHBoxLayout()
        self.optionsLayout2.setObjectName("optionsLayout2")
        self.thumbnailCheck = QtWidgets.QCheckBox(self.optionsGroup)
        self.thumbnailCheck.setObjectName("thumbnailCheck")
        self.optionsLayout2.addWidget(self.thumbnailCheck)
        self.thumbnailHintLabel = QtWidgets.QLabel(self.optionsGroup)
        self.thumbnailHintLabel.setObjectName("thumbnailHintLabel")
        self.optionsLayout2.addWidget(self.thumbnailHintLabel)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.optionsLayout2.addItem(spacerItem7)
        self.optionsGroupLayout.addLayout(self.optionsLayout2)
        self.optionsLayout3 = QtWidgets.QHBoxLayout()
        self.optionsLayout3.setObjectName("optionsLayout3")
        self.metadataCheck = QtWidgets.QCheckBox(self.optionsGroup)
        self.metadataCheck.setObjectName("metadataCheck")
        self.optionsLayout3.addWidget(self.metadataCheck)
        self.metadataHintLabel = QtWidgets.QLabel(self.optionsGroup)
        self.metadataHintLabel.setObjectName("metadataHintLabel")
        self.optionsLayout3.addWidget(self.metadataHintLabel)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.optionsLayout3.addItem(spacerItem8)
        self.optionsGroupLayout.addLayout(self.optionsLayout3)
        self.settingsTabLayout.addWidget(self.optionsGroup)
        self.ffmpegGroup = QtWidgets.QGroupBox(self.settingsTab)
        self.ffmpegGroup.setObjectName("ffmpegGroup")
        self.ffmpegGroupLayout = QtWidgets.QVBoxLayout(self.ffmpegGroup)
        self.ffmpegGroupLayout.setObjectName("ffmpegGroupLayout")
        self.ffmpegPathLayout = QtWidgets.QHBoxLayout()
        self.ffmpegPathLayout.setObjectName("ffmpegPathLayout")
        self.ffmpegLabel = QtWidgets.QLabel(self.ffmpegGroup)
        self.ffmpegLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.ffmpegLabel.setObjectName("ffmpegLabel")
        self.ffmpegPathLayout.addWidget(self.ffmpegLabel)
        self.ffmpegPathEdit = QtWidgets.QLineEdit(self.ffmpegGroup)
        self.ffmpegPathEdit.setObjectName("ffmpegPathEdit")
        self.ffmpegPathLayout.addWidget(self.ffmpegPathEdit)
        self.browseFfmpegBtn = QtWidgets.QPushButton(self.ffmpegGroup)
        self.browseFfmpegBtn.setMaximumSize(QtCore.QSize(80, 16777215))
        self.browseFfmpegBtn.setObjectName("browseFfmpegBtn")
        self.ffmpegPathLayout.addWidget(self.browseFfmpegBtn)
        self.downloadFfmpegBtn = QtWidgets.QPushButton(self.ffmpegGroup)
        self.downloadFfmpegBtn.setMaximumSize(QtCore.QSize(120, 16777215))
        self.downloadFfmpegBtn.setObjectName("downloadFfmpegBtn")
        self.ffmpegPathLayout.addWidget(self.downloadFfmpegBtn)
        self.ffmpegGroupLayout.addLayout(self.ffmpegPathLayout)
        self.ffmpegHintLabel = QtWidgets.QLabel(self.ffmpegGroup)
        self.ffmpegHintLabel.setObjectName("ffmpegHintLabel")
        self.ffmpegGroupLayout.addWidget(self.ffmpegHintLabel)
        self.settingsTabLayout.addWidget(self.ffmpegGroup)
        self.settingsButtonsLayout = QtWidgets.QHBoxLayout()
        self.settingsButtonsLayout.setObjectName("settingsButtonsLayout")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.settingsButtonsLayout.addItem(spacerItem9)
        self.saveSettingsBtn = QtWidgets.QPushButton(self.settingsTab)
        self.saveSettingsBtn.setMinimumSize(QtCore.QSize(120, 36))
        self.saveSettingsBtn.setObjectName("saveSettingsBtn")
        self.settingsButtonsLayout.addWidget(self.saveSettingsBtn)
        self.resetSettingsBtn = QtWidgets.QPushButton(self.settingsTab)
        self.resetSettingsBtn.setMinimumSize(QtCore.QSize(120, 36))
        self.resetSettingsBtn.setObjectName("resetSettingsBtn")
        self.settingsButtonsLayout.addWidget(self.resetSettingsBtn)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.settingsButtonsLayout.addItem(spacerItem10)
        self.settingsTabLayout.addLayout(self.settingsButtonsLayout)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.settingsTabLayout.addItem(spacerItem11)
        self.tabWidget.addTab(self.settingsTab, "")
        self.helpTab = QtWidgets.QWidget()
        self.helpTab.setObjectName("helpTab")
        self.helpTabLayout = QtWidgets.QVBoxLayout(self.helpTab)
        self.helpTabLayout.setObjectName("helpTabLayout")
        self.usageGroup = QtWidgets.QGroupBox(self.helpTab)
        self.usageGroup.setObjectName("usageGroup")
        self.usageLayout = QtWidgets.QVBoxLayout(self.usageGroup)
        self.usageLayout.setObjectName("usageLayout")
        self.usageText = QtWidgets.QTextEdit(self.usageGroup)
        self.usageText.setReadOnly(True)
        self.usageText.setObjectName("usageText")
        self.usageLayout.addWidget(self.usageText)
        self.helpTabLayout.addWidget(self.usageGroup)
        self.supportedSitesGroup = QtWidgets.QGroupBox(self.helpTab)
        self.supportedSitesGroup.setObjectName("supportedSitesGroup")
        self.supportedSitesLayout = QtWidgets.QVBoxLayout(self.supportedSitesGroup)
        self.supportedSitesLayout.setObjectName("supportedSitesLayout")
        self.sitesIntroLabel = QtWidgets.QLabel(self.supportedSitesGroup)
        self.sitesIntroLabel.setObjectName("sitesIntroLabel")
        self.supportedSitesLayout.addWidget(self.sitesIntroLabel)
        self.sitesText = QtWidgets.QTextEdit(self.supportedSitesGroup)
        self.sitesText.setReadOnly(True)
        self.sitesText.setObjectName("sitesText")
        self.supportedSitesLayout.addWidget(self.sitesText)
        self.helpTabLayout.addWidget(self.supportedSitesGroup)
        self.versionLayout = QtWidgets.QHBoxLayout()
        self.versionLayout.setObjectName("versionLayout")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.versionLayout.addItem(spacerItem12)
        self.versionLabel = QtWidgets.QLabel(self.helpTab)
        self.versionLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.versionLabel.setObjectName("versionLabel")
        self.versionLayout.addWidget(self.versionLabel)
        self.helpTabLayout.addLayout(self.versionLayout)
        self.tabWidget.addTab(self.helpTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionContact = QtWidgets.QAction(MainWindow)
        self.actionContact.setObjectName("actionContact")
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionContact)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "万能视频下载器"))
        self.tabWidget.setStyleSheet(_translate("MainWindow", "QTabWidget::pane {\n"
"    background-color: white;\n"
"    border: 1px solid #ddd;\n"
"    border-radius: 4px;\n"
"}\n"
"QTabBar::tab {\n"
"    background-color: #f0f0f0;\n"
"    color: #333;\n"
"    padding: 8px 16px;\n"
"    border: 1px solid #ddd;\n"
"    border-bottom: none;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    margin-right: 2px;\n"
"}\n"
"QTabBar::tab:selected {\n"
"    background-color: white;\n"
"    color: #2196F3;\n"
"    border-bottom: 2px solid #2196F3;\n"
"}\n"
"QTabBar::tab:hover:!selected {\n"
"    background-color: #e0e0e0;\n"
"}"))
        self.urlGroup.setTitle(_translate("MainWindow", "视频链接"))
        self.label.setText(_translate("MainWindow", "视频网址："))
        self.videoUrl.setPlaceholderText(_translate("MainWindow", "粘贴视频网址，例如：https://www.youtube.com/watch?v=xxx"))
        self.clearUrlBtn.setText(_translate("MainWindow", "清空"))
        self.downloadBtn.setStyleSheet(_translate("MainWindow", "QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #3d8b40;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #cccccc;\n"
"}"))
        self.downloadBtn.setText(_translate("MainWindow", "开始下载"))
        self.cancelBtn.setStyleSheet(_translate("MainWindow", "QPushButton {\n"
"    background-color: #f44336;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #d32f2f;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #cccccc;\n"
"}"))
        self.cancelBtn.setText(_translate("MainWindow", "取消"))
        self.progressGroup.setTitle(_translate("MainWindow", "下载进度"))
        self.downloadStatus.setFormat(_translate("MainWindow", "%p%"))
        self.progressLabel.setText(_translate("MainWindow", "就绪"))
        self.contactGroup.setTitle(_translate("MainWindow", "关于我们"))
        self.adLabel.setText(_translate("MainWindow", "<html><head/><body><h3 style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:large; font-weight:600; color:#2196f3;\">🚀 专业互联网软件定制开发</span></h3><p align=\"justify\"><span style=\" font-size:12px; color:#666666;\">• AI人工智能应用集成开发</span></p><p align=\"justify\"><span style=\" font-size:12px; color:#666666;\">• 桌面应用 • Web 应用 • 移动端<br/>• 微信小程序 • 手机APP • 自动化脚本 </span></p><p align=\"justify\"><span style=\" font-size:12px; color:#666666;\">• 各种企业信息化系统定制开发等。</span></p><p><span style=\" font-size:13px; font-weight:600; color:#1976d2;\">✨ 承接各种企业信息化软件定制开发需求，欢迎咨询！</span></p></body></html>"))
        self.websiteBtn.setStyleSheet(_translate("MainWindow", "QPushButton {\n"
"    background-color: #2196F3;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #1976D2;\n"
"}"))
        self.websiteBtn.setText(_translate("MainWindow", "🌐 访问官网"))
        self.contactPageBtn.setStyleSheet(_translate("MainWindow", "QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #388E3C;\n"
"}"))
        self.contactPageBtn.setText(_translate("MainWindow", "📧 联系我们"))
        self.qqGroup.setTitle(_translate("MainWindow", "QQ"))
        self.qqQrLabel.setStyleSheet(_translate("MainWindow", "border: 1px solid #2196F3;\n"
"border-radius: 4px;"))
        self.qqQrLabel.setText(_translate("MainWindow", "加载中..."))
        self.qqInfoLabel.setStyleSheet(_translate("MainWindow", "font-size: 11px;\n"
"font-weight: bold;\n"
"color: #333;"))
        self.qqInfoLabel.setText(_translate("MainWindow", "932256355"))
        self.wechatGroup.setTitle(_translate("MainWindow", "微信公众号"))
        self.wechatQrLabel.setStyleSheet(_translate("MainWindow", "border: 1px solid #4CAF50;\n"
"border-radius: 4px;"))
        self.wechatQrLabel.setText(_translate("MainWindow", "加载中..."))
        self.wechatInfoLabel.setStyleSheet(_translate("MainWindow", "font-size: 11px;\n"
"font-weight: bold;\n"
"color: #333;"))
        self.wechatInfoLabel.setText(_translate("MainWindow", "扫码关注"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.downloadTab), _translate("MainWindow", "视频下载"))
        self.pathGroup.setTitle(_translate("MainWindow", "保存路径"))
        self.pathLabel.setText(_translate("MainWindow", "保存路径："))
        self.pathEdit.setText(_translate("MainWindow", "~/Downloads"))
        self.browsePathBtn.setText(_translate("MainWindow", "浏览..."))
        self.pathHintLabel.setStyleSheet(_translate("MainWindow", "color: #888;\n"
"font-size: 12px;"))
        self.pathHintLabel.setText(_translate("MainWindow", "💡 提示：下载的视频文件将保存到此目录"))
        self.formatGroup.setTitle(_translate("MainWindow", "视频格式"))
        self.formatLabel.setText(_translate("MainWindow", "选择格式："))
        self.formatCombo.setCurrentText(_translate("MainWindow", "最佳质量"))
        self.formatCombo.setItemText(0, _translate("MainWindow", "最佳质量"))
        self.formatCombo.setItemText(1, _translate("MainWindow", "最佳视频 + 音频"))
        self.formatCombo.setItemText(2, _translate("MainWindow", "仅音频"))
        self.formatCombo.setItemText(3, _translate("MainWindow", "仅音频 (mp3)"))
        self.formatCombo.setItemText(4, _translate("MainWindow", "仅音频 (m4a)"))
        self.formatCombo.setItemText(5, _translate("MainWindow", "仅视频 (mp4)"))
        self.formatCombo.setItemText(6, _translate("MainWindow", "720p"))
        self.formatCombo.setItemText(7, _translate("MainWindow", "480p"))
        self.formatHintLabel.setStyleSheet(_translate("MainWindow", "color: #888;\n"
"font-size: 12px;"))
        self.formatHintLabel.setText(_translate("MainWindow", "💡 提示：选择不同的视频质量和格式，音频格式会自动提取"))
        self.optionsGroup.setTitle(_translate("MainWindow", "下载选项"))
        self.subtitleCheck.setText(_translate("MainWindow", "下载字幕"))
        self.subtitleHintLabel.setStyleSheet(_translate("MainWindow", "color: #888;\n"
"font-size: 11px;"))
        self.subtitleHintLabel.setText(_translate("MainWindow", "自动下载视频字幕文件"))
        self.thumbnailCheck.setText(_translate("MainWindow", "下载缩略图"))
        self.thumbnailHintLabel.setStyleSheet(_translate("MainWindow", "color: #888;\n"
"font-size: 11px;"))
        self.thumbnailHintLabel.setText(_translate("MainWindow", "下载视频封面图片"))
        self.metadataCheck.setText(_translate("MainWindow", "嵌入元数据"))
        self.metadataHintLabel.setStyleSheet(_translate("MainWindow", "color: #888;\n"
"font-size: 11px;"))
        self.metadataHintLabel.setText(_translate("MainWindow", "将视频标题、作者等信息嵌入到文件中"))
        self.ffmpegGroup.setTitle(_translate("MainWindow", "FFmpeg 配置"))
        self.ffmpegLabel.setText(_translate("MainWindow", "FFmpeg 路径："))
        self.ffmpegPathEdit.setPlaceholderText(_translate("MainWindow", "自动检测或手动选择 FFmpeg 路径"))
        self.browseFfmpegBtn.setText(_translate("MainWindow", "浏览..."))
        self.downloadFfmpegBtn.setText(_translate("MainWindow", "自动下载"))
        self.ffmpegHintLabel.setStyleSheet(_translate("MainWindow", "color: #888;\n"
"font-size: 12px;"))
        self.ffmpegHintLabel.setText(_translate("MainWindow", "💡 FFmpeg 用于合并视频和音频流，下载高清视频时必需"))
        self.saveSettingsBtn.setStyleSheet(_translate("MainWindow", "QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    border-radius: 6px;\n"
"    font-weight: bold;\n"
"    padding: 5px 15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #3d8b40;\n"
"}"))
        self.saveSettingsBtn.setText(_translate("MainWindow", "💾 保存设置"))
        self.resetSettingsBtn.setStyleSheet(_translate("MainWindow", "QPushButton {\n"
"    background-color: #f44336;\n"
"    color: white;\n"
"    border-radius: 6px;\n"
"    font-weight: bold;\n"
"    padding: 5px 15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #da190b;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #b71c1c;\n"
"}"))
        self.resetSettingsBtn.setText(_translate("MainWindow", "🔄 恢复默认"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settingsTab), _translate("MainWindow", "设置"))
        self.usageGroup.setTitle(_translate("MainWindow", "📖 使用方法"))
        self.usageText.setStyleSheet(_translate("MainWindow", "QTextEdit {\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #ddd;\n"
"    border-radius: 6px;\n"
"    padding: 8px;\n"
"}"))
        self.usageText.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'-apple-system\',\'BlinkMacSystemFont\',\'PingFang SC\',\'Microsoft YaHei\',\'sans-serif\'; font-size:16px; font-weight:600; color:#2196f3;\">📌 快速上手</span></p>\n"
"<ol style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-family:\'-apple-system\',\'BlinkMacSystemFont\',\'PingFang SC\',\'Microsoft YaHei\',\'sans-serif\'; font-size:14px;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14px; font-weight:600;\">复制视频链接</span><span style=\" font-size:14px;\">：从浏览器中复制您想下载的视频网址</span></li>\n"
"<li style=\" font-family:\'-apple-system\',\'BlinkMacSystemFont\',\'PingFang SC\',\'Microsoft YaHei\',\'sans-serif\'; font-size:14px;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14px; font-weight:600;\">粘贴到输入框</span><span style=\" font-size:14px;\">：将链接粘贴到本程序的&quot;视频网址&quot;输入框中</span></li>\n"
"<li style=\" font-family:\'-apple-system\',\'BlinkMacSystemFont\',\'PingFang SC\',\'Microsoft YaHei\',\'sans-serif\'; font-size:14px;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14px; font-weight:600;\">选择格式</span><span style=\" font-size:14px;\">：在&quot;设置&quot;标签页中选择您需要的视频格式和质量</span></li>\n"
"<li style=\" font-family:\'-apple-system\',\'BlinkMacSystemFont\',\'PingFang SC\',\'Microsoft YaHei\',\'sans-serif\'; font-size:14px;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14px; font-weight:600;\">开始下载</span><span style=\" font-size:14px;\">：点击&quot;开始下载&quot;按钮，等待下载完成</span></li>\n"
"<li style=\" font-family:\'-apple-system\',\'BlinkMacSystemFont\',\'PingFang SC\',\'Microsoft YaHei\',\'sans-serif\'; font-size:14px;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14px; font-weight:600;\">查看文件</span><span style=\" font-size:14px;\">：下载完成后，视频文件将保存在您设置的保存路径中</span></li></ol>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'-apple-system\',\'BlinkMacSystemFont\',\'PingFang SC\',\'Microsoft YaHei\',\'sans-serif\'; font-size:16px; font-weight:600; color:#2196f3;\">⚙️ 高级设置</span></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-family:\'-apple-system\',\'BlinkMacSystemFont\',\'PingFang SC\',\'Microsoft YaHei\',\'sans-serif\'; font-size:14px;\" style=\" margin-top:8px; margin-bottom:8px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14px; font-weight:600;\">字幕下载</span><span style=\" font-size:14px;\">：勾选&quot;下载字幕&quot;选项，可自动下载视频字幕</span></li>\n"
"<li style=\" font-family:\'-apple-system\',\'BlinkMacSystemFont\',\'PingFang SC\',\'Microsoft YaHei\',\'sans-serif\'; font-size:14px;\" style=\" margin-top:8px; margin-bottom:8px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14px; font-weight:600;\">缩略图</span><span style=\" font-size:14px;\">：勾选&quot;下载缩略图&quot;选项，可下载视频封面图</span></li>\n"
"<li style=\" font-family:\'-apple-system\',\'BlinkMacSystemFont\',\'PingFang SC\',\'Microsoft YaHei\',\'sans-serif\'; font-size:14px;\" style=\" margin-top:8px; margin-bottom:8px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14px; font-weight:600;\">元数据</span><span style=\" font-size:14px;\">：勾选&quot;嵌入元数据&quot;选项，可将视频标题、作者等信息嵌入文件</span></li></ul>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'-apple-system\',\'BlinkMacSystemFont\',\'PingFang SC\',\'Microsoft YaHei\',\'sans-serif\'; font-size:16px; font-weight:600; color:#ff5722;\">💡 小提示</span></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-family:\'-apple-system\',\'BlinkMacSystemFont\',\'PingFang SC\',\'Microsoft YaHei\',\'sans-serif\'; font-size:14px;\" style=\" margin-top:8px; margin-bottom:8px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14px;\">下载过程中可以随时点击&quot;取消&quot;按钮中断下载</span></li>\n"
"<li style=\" font-family:\'-apple-system\',\'BlinkMacSystemFont\',\'PingFang SC\',\'Microsoft YaHei\',\'sans-serif\'; font-size:14px;\" style=\" margin-top:8px; margin-bottom:8px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14px;\">支持下载速度较慢时，建议选择较低质量格式</span></li>\n"
"<li style=\" font-family:\'-apple-system\',\'BlinkMacSystemFont\',\'PingFang SC\',\'Microsoft YaHei\',\'sans-serif\'; font-size:14px;\" style=\" margin-top:8px; margin-bottom:8px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14px;\">部分网站可能需要等待或重试才能成功下载</span></li></ul></body></html>"))
        self.supportedSitesGroup.setTitle(_translate("MainWindow", "🌐 支持的视频网站"))
        self.sitesIntroLabel.setStyleSheet(_translate("MainWindow", "color: #666;\n"
"font-size: 13px;\n"
"padding: 5px;"))
        self.sitesIntroLabel.setText(_translate("MainWindow", "万能视频下载器支持超过 1000 个视频网站，以下是一些常用的网站："))
        self.sitesText.setStyleSheet(_translate("MainWindow", "QTextEdit {\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #ddd;\n"
"    border-radius: 6px;\n"
"    padding: 8px;\n"
"}"))
        self.sitesText.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:8px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'-apple-system\',\'BlinkMacSystemFont\',\'PingFang SC\',\'Microsoft YaHei\',\'sans-serif\'; font-size:14px; font-weight:600; color:#e91e63;\">🎬 国际主流平台</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'-apple-system\',\'BlinkMacSystemFont\',\'PingFang SC\',\'Microsoft YaHei\',\'sans-serif\'; font-size:13px;\">• YouTube（包括 Shorts）</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'-apple-system\',\'BlinkMacSystemFont\',\'PingFang SC\',\'Microsoft YaHei\',\'sans-serif\'; font-size:13px;\">• Bilibili（支持 4K 高清）</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'-apple-system\',\'BlinkMacSystemFont\',\'PingFang SC\',\'Microsoft YaHei\',\'sans-serif\'; font-size:13px;\">• Twitch、Vimeo、Dailymotion</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'-apple-system\',\'BlinkMacSystemFont\',\'PingFang SC\',\'Microsoft YaHei\',\'sans-serif\'; font-size:13px;\">• Facebook、Instagram、Twitter</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:8px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'-apple-system\',\'BlinkMacSystemFont\',\'PingFang SC\',\'Microsoft YaHei\',\'sans-serif\'; font-size:14px; font-weight:600; color:#ff9800;\">🇨🇳 国内视频平台</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'-apple-system\',\'BlinkMacSystemFont\',\'PingFang SC\',\'Microsoft YaHei\',\'sans-serif\'; font-size:13px;\">• 优酷、腾讯视频、爱奇艺</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'-apple-system\',\'BlinkMacSystemFont\',\'PingFang SC\',\'Microsoft YaHei\',\'sans-serif\'; font-size:13px;\">• 抖音、快手（短视频）</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'-apple-system\',\'BlinkMacSystemFont\',\'PingFang SC\',\'Microsoft YaHei\',\'sans-serif\'; font-size:13px;\">• 西瓜视频、今日头条</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'-apple-system\',\'BlinkMacSystemFont\',\'PingFang SC\',\'Microsoft YaHei\',\'sans-serif\'; font-size:13px;\">• 哔哩哔哩（B 站）</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:8px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'-apple-system\',\'BlinkMacSystemFont\',\'PingFang SC\',\'Microsoft YaHei\',\'sans-serif\'; font-size:14px; font-weight:600; color:#4caf50;\">🎵 音乐平台</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'-apple-system\',\'BlinkMacSystemFont\',\'PingFang SC\',\'Microsoft YaHei\',\'sans-serif\'; font-size:13px;\">• YouTube Music</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'-apple-system\',\'BlinkMacSystemFont\',\'PingFang SC\',\'Microsoft YaHei\',\'sans-serif\'; font-size:13px;\">• SoundCloud、Bandcamp</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'-apple-system\',\'BlinkMacSystemFont\',\'PingFang SC\',\'Microsoft YaHei\',\'sans-serif\'; font-size:13px;\">• 网易云音乐、QQ音乐</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:8px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'-apple-system\',\'BlinkMacSystemFont\',\'PingFang SC\',\'Microsoft YaHei\',\'sans-serif\'; font-size:14px; font-weight:600; color:#9c27b0;\">📺 直播平台</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'-apple-system\',\'BlinkMacSystemFont\',\'PingFang SC\',\'Microsoft YaHei\',\'sans-serif\'; font-size:13px;\">• Twitch、YouTube Live</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'-apple-system\',\'BlinkMacSystemFont\',\'PingFang SC\',\'Microsoft YaHei\',\'sans-serif\'; font-size:13px;\">• 斗鱼、虎牙</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'-apple-system\',\'BlinkMacSystemFont\',\'PingFang SC\',\'Microsoft YaHei\',\'sans-serif\'; font-size:13px; color:#1976d2;\">💡 完整支持列表请访问：https://dev.tekin.cn </span></p></body></html>"))
        self.versionLabel.setStyleSheet(_translate("MainWindow", "color: #999;\n"
"font-size: 11px;\n"
"padding: 5px;"))
        self.versionLabel.setText(_translate("MainWindow", "当前版本：加载中..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.helpTab), _translate("MainWindow", "使用帮助"))
        self.menuFile.setTitle(_translate("MainWindow", "文件"))
        self.menuHelp.setTitle(_translate("MainWindow", "帮助"))
        self.actionExit.setText(_translate("MainWindow", "退出"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionAbout.setText(_translate("MainWindow", "关于"))
        self.actionContact.setText(_translate("MainWindow", "联系我们"))
