# Autogenerated by devscripts/update-version.py

__version__ = '2026.02.13'

RELEASE_GIT_HEAD = 'afef0a06aee5d579cc5be9290d32781cab76bb9c'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'

ORIGIN = 'local'

_pkg_version = '2026.02.13'
