# Autogenerated by devscripts/update-version.py

__version__ = '2026.02.12.3'

RELEASE_GIT_HEAD = 'd1311148c25a7d8bf6b0b7b59bca6410d2bbea35'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'

ORIGIN = 'local'

_pkg_version = '2026.02.12.3'
