# Autogenerated by devscripts/update-version.py

__version__ = '2026.02.12.2'

RELEASE_GIT_HEAD = '377129a19c2d0815ec8cb1103a67aa46583df382'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'

ORIGIN = 'local'

_pkg_version = '2026.02.12.2'
